language: node_js
sudo: false
node_js:
  - '6'

cache:
  yarn: true

env:
  global:
    - CXX=g++-4.8  # node 4 likes the G++ v4.8 compiler

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  code_climate:
    repo_token: '......'

before_script:
  - npm install -g npm@latest
  - npm install -g gulp

script:
  - gulp test
  - gulp build
