/**
 * ngAdsense AngularJS module for Google AdSense advertisements.
 * @author Peter Szrnka (szrnka.peter@gmail.com)
 * @version 1.0a
 */
var ngAdSense = angular.module('ngAdsense', []);
ngAdSense.constant('SCRIPT_URL', 'http://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js');

/**
 * @directive adsenseDirective
 * @cfg adClient AdSense Client id. (Mandatory field)
 * @cfg adSlot AdSense Slot id. (Mandatory field)
 * @cfg cssStyle CSS customization generated by AdSense website. (Mandatory field)
 */
ngAdSense.directive('adsenseDirective', function(SCRIPT_URL) {
	return {
		restrict : 'E',
		replace : true,
		template : '<div><ins class="adsbygoogle" style="{{cssStyle}}" data-ad-client="{{adClient}}" data-ad-slot="{{adSlot}}"></ins></div>',
		scope : {
			adClient : '@',
			adSlot : '@',
			cssStyle : '@'
		},
		link : function(scope, element) {
			var s = document.createElement('script');
			s.src = SCRIPT_URL;
			document.body.appendChild(s);
			(adsbygoogle = window.adsbygoogle || []).push({});
		}
	};
});